.PHONY: build cluster test

default: build

build:
	go build -o bin/swarm    github.com/echochain/echo-core/cmd/swarm
	go build -o bin/gecho     github.com/echochain/echo-core/cmd/gecho
	go build -o bin/bootnode github.com/echochain/echo-core/cmd/bootnode

cluster: build
	scripts/boot-cluster.sh

test:
	go test -v github.com/echochain/echo-core/swarm/...
